### ISSUE TITLE
File does not exist 'ui/ui_res.qrc'

### ISSUE THREAD

**Issue by reinauer** [briansune/SPD1000x_GUI_SCPI#1]
Compile.txt states

```
pyrcc5 -o ui_res_rc.py ui/ui_res.qrc
```

But when I try to run it, I get:
```
/usr/lib/python3/dist-packages/PyQt5/pyrcc_main.py: File does not exist 'ui/ui_res.qrc'
```

**Comment by briansune** [comment]
@reinauer 

I guess you are using compile and run method rather than the binary method.

Make sure you had install PyQt5 library and designer is able to open.

The code had been running years and you can even run without the GUI and simply run the SCPI control.

Qrc you can create via designer or please find the update missing files useful.

**Comment by reinauer** [comment]
I can run the program by running python main.py and it works.

Sorry I should've known a bit more about Qt Designer . I was able to produce the file in designer. Thank you!
